FROM openjdk:8

RUN mkdir /work && cd /work

RUN git clone https://github.com/axelor/axelor-development-kit.git -b wip /work/axelor-development-kit
RUN git clone https://github.com/axelor/abs-webapp.git -b wip /work/abs-webapp
RUN git clone https://github.com/axelor/axelor-business-suite.git -b wip /work/abs-webapp/modules/abs

RUN rm -rf /work/abs-webapp/modules/abs/axelor-account && \
    # rm -rf /work/abs-webapp/modules/abs/axelor-admin && \
    rm -rf /work/abs-webapp/modules/abs/axelor-bank-payment && \
    # rm -rf /work/abs-webapp/modules/abs/axelor-base && \
    rm -rf /work/abs-webapp/modules/abs/axelor-business-production && \
    rm -rf /work/abs-webapp/modules/abs/axelor-business-project && \
    rm -rf /work/abs-webapp/modules/abs/axelor-cash-management && \
    rm -rf /work/abs-webapp/modules/abs/axelor-client-portal && \
    rm -rf /work/abs-webapp/modules/abs/axelor-contract && \
    # rm -rf /work/abs-webapp/modules/abs/axelor-crm && \
    # rm -rf /work/abs-webapp/modules/abs/axelor-exception && \
    rm -rf /work/abs-webapp/modules/abs/axelor-fleet && \
    rm -rf /work/abs-webapp/modules/abs/axelor-helpdesk && \
    rm -rf /work/abs-webapp/modules/abs/axelor-human-resource && \
    rm -rf /work/abs-webapp/modules/abs/axelor-marketing && \
    # rm -rf /work/abs-webapp/modules/abs/axelor-message && \
    rm -rf /work/abs-webapp/modules/abs/axelor-production && \
    rm -rf /work/abs-webapp/modules/abs/axelor-project && \
    rm -rf /work/abs-webapp/modules/abs/axelor-purchase && \
    rm -rf /work/abs-webapp/modules/abs/axelor-quality && \
    rm -rf /work/abs-webapp/modules/abs/axelor-sale && \
    rm -rf /work/abs-webapp/modules/abs/axelor-stock && \
    rm -rf /work/abs-webapp/modules/abs/axelor-studio && \
    rm -rf /work/abs-webapp/modules/abs/axelor-supplier-management && \
    rm -rf /work/abs-webapp/modules/abs/axelor-supplychain && \
    rm -rf /work/abs-webapp/modules/abs/axelor-talent
    # rm -rf /work/abs-webapp/modules/abs/axelor-tool && \

COPY ./axelor-development-kit /work/axelor-development-kit
COPY ./abs-webapp /work/abs-webapp
COPY ./.m2 /root/.m2

RUN cd /work/axelor-development-kit && ./gradlew clean publishToMavenLocal --no-daemon -x test

# expose the working directory, the Tomcat port, the BrowserSync ports
USER root
# ENV PATH $PATH:/work/bin
# WORKDIR "/work/abs-webapp"
# VOLUME ["/work/abs-webapp"]
EXPOSE 8080 9000 3001
# CMD ["./gradlew", "clean --no-daemon run --port 8181 -x test", "/work/abs-webapp"]
CMD echo "The application will start in 5s..." && \
    sleep 5 && \
    /work/abs-webapp/gradlew clean --no-daemon run --port 8080 -x test